UIU-2503: Display preferred name in Checkout and Requests user modal
folio-org/ui-plugin-find-user pull request #195
Opened 2022-02-15 15:39 UTC by Javokhir12

## Purpose
- Display preferred name in the user search modal in Checkout and Requests
- If user has `preferredFirstName` then display `LastName`, `PreferredFirstName` `(FirstName)` `MiddleName` in result list
- if user doesn't have  `preferredFirstName` then display `LastName`, `FirstName` `MiddleName` in result list
- Refs: https://issues.folio.org/browse/UIU-2503

## Approach
- Refactor `getFullName` function to include `preferredFirstName`
- Added `eslint-import-resolver-webpack` plugin to resolve eslint error `unable to resolve path to module`. See in screenshots

## Screenshots
<img src="https://user-images.githubusercontent.com/89512426/154093998-6d1ce69a-1533-4d17-ab90-e781dff171c4.png" width="250" height="200" />  <img src="https://user-images.githubusercontent.com/89512426/154094250-85662fcc-29ff-403a-be31-32a2614625a5.png" width="250" height="200" /> <img src="https://user-images.githubusercontent.com/89512426/154095669-3930ba6e-e501-46b6-afb2-438ce2a360da.png" width="250" height="200" />

2022-02-15 15:44 UTC, Javokhir12 commented
Hi @zburke , @mkuklis . Please take a look

2022-02-15 18:24 UTC, zburke commented on src/UserSearchView.js
> +  const preferredFirstName = get(user, ['personal', 'preferredFirstName'], '');
Alternatively, we can use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) and [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) instead of lodash.get: 
```
let firstName = user?.personal?.firstName ?? '';
```
(These weren't around back in the olden days 👴  of 2019 😆  when we wrote this module.)

2022-02-15 18:48 UTC, zburke commented on .eslintrc
> +  }
Why is this change here? Locally, I don't see any lint warnings/errors when I test this branch locally.

2022-02-15 18:48 UTC, zburke commented on src/UserSearchView.js
> +
Pedantic: this extra whitespace looks unintentional. Can you remove it?

2022-02-15 19:24 UTC, Javokhir12 commented on src/UserSearchView.js
> +
good catch)

2022-02-15 19:24 UTC, Javokhir12 commented on .eslintrc
> +  }
@zburke I am getting following error if I remove this rule:
<img src="https://user-images.githubusercontent.com/89512426/154133647-89cd5fd7-cc2a-4d75-ae18-e6a58b90aef3.png" width="150" height="100" />

2022-02-15 20:29 UTC, zburke commented on .eslintrc
> +  }
That doesn't make any sense. "Search" _is_ on its own line! Lint is clean for me: 
```
$ git diff
diff --git a/.eslintrc b/.eslintrc
index 349124b..e937ec8 100644
--- a/.eslintrc
+++ b/.eslintrc
@@ -1,7 +1,4 @@
 {
   "parser": "babel-eslint",
-  "extends": "@folio/eslint-config-stripes",
-  "rules": {
-    "react/jsx-one-expression-per-line": 0
-  }
+  "extends": "@folio/eslint-config-stripes"
 }
ui-plugin-find-user(UIU-2503)*
$ yarn lint
yarn run v1.22.11
$ eslint .
✨  Done in 3.86s.
ui-plugin-find-user(UIU-2503)*
$ 
```
Can we see if it runs cleanly in CI without that change? As much as possible, I try to leave lint rules alone so they remain consistent across our repositories. 

Related, sorta, but not your fault: "Search" shouldn't be `Search`! It should be 
```
<FormattedMessage id="ui-plugin-find-user.searchFieldLabel" />
```
Can you fix that here or in a separate PR if you view it as a separate concern? Thank you!

2022-02-15 20:31 UTC, zburke requested changes

2022-02-15 20:31 UTC, zburke commented on CHANGELOG.md
> +* Display preferred name in the user search modal in Checkout and Requests. UIU-2503.
Since 6.0.0 was already released, this line should instead be added under a new header, like this: 
```
## 6.1.0 IN PROGRESS

* Display preferred name in the user search modal in Checkout and Requests. UIU-2503.

## [6.0.0] ...
```

2022-02-16 08:28 UTC, Javokhir12 commented
Hi @zburke . Could you merge if everything is ok. Thank you!

2022-02-16 10:38 UTC, zburke approved these changes

2022-02-16 12:16 UTC, merged