UIPFU-71: add `initialSelectedUsers` property
folio-org/ui-plugin-find-user pull request #234
Opened 2023-08-01 09:40 UTC by alisher-epam

## JIRA ISUUE - [UIPFU-71](https://issues.folio.org/browse/UIPFU-71)
The feature is created based on this [Jira task](https://issues.folio.org/browse/UIU-2873)
As a user,
I want to see the assigned users list when opening the find users modal
so that I don't cause duplicate errors when assigning new users

Scenario:
- Given the user has already been assigned a users list
- When click the "Assign/unassign" button
- Then user should see the list of users already selected in the modal

![Screenshot 2023-08-01 at 2 35 59 PM](https://github.com/folio-org/ui-plugin-find-user/assets/116072773/ba33ff14-3f60-4bae-91ea-9649df2b4765)

2023-08-03 09:02 UTC, usavkov-epam approved these changes

2023-08-03 12:03 UTC, Dmitriy-Litvinenko approved these changes

2023-08-03 13:13 UTC, Terala-Priyanka requested changes
Could you add unit tests?

2023-08-03 17:14 UTC, alisher-epam commented
@Terala-Priyanka I have added a unit test.

2023-08-04 10:01 UTC, merged

2023-08-04 10:02 UTC, alisher-epam commented
@Terala-Priyanka I have merged the PR after adding unit tests since you are off today.

2023-08-04 14:57 UTC, zburke reviewed
The tests are not quite right and need to be cleaned up before this can be merged. 

Also, the more I think about this, the more I wonder it feels like a much simpler solution would be just suck the user lists through set like `[...new Set(initial, selected)]` before making the API query. I guess that's not as nice since the modal won't reflect initial selected users, but it sure is simpler. Dunno; maybe worth considering though.

2023-08-04 14:57 UTC, zburke commented on src/PluginFindUser.js
> +  }),
Do we really need all this data? I expected this to just be an array of IDs.

2023-08-07 07:01 UTC, alisher-epam commented on test/bigtest/tests/findUser-test.js
> +    expect(result).to.equal(undefined);
Agree. I have not seen anyone writing to check prop validations as well. However, I have extracted the props inside `shapes.js` and the sonar showed 0% coverage and I was requested to write a test for resolving this issue.

2023-08-07 07:05 UTC, alisher-epam commented on test/bigtest/tests/findUser-test.js
> +      });
This is an optional prop and left it purposefully.