UIPFU-74 Support fetch users from different tenants
folio-org/ui-plugin-find-user pull request #238
Opened 2023-08-11 05:33 UTC by NikitaSedyx

## Purpose

## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-08-11 05:44 UTC, usavkov-epam approved these changes

2023-08-11 05:45 UTC, alisher-epam approved these changes

2023-08-11 07:16 UTC, Terala-Priyanka approved these changes

2023-08-16 19:19 UTC, zburke requested changes
Don't fight lint. If you think the rules are wrong, then open a Jira explaining which rule needs to be changed and why, and add a comment here explaining why you are smarter than lint. Otherwise, follow its advice.

2023-08-16 19:19 UTC, zburke commented on src/UserSearchContainer.js
> +    tenantId: PropTypes.string.isRequired,
Do not disable lint without a comment explaining why. Even better, do not disable lint; heed its advice.

2023-08-17 04:10 UTC, NikitaSedyx commented on src/UserSearchContainer.js
> +    tenantId: PropTypes.string.isRequired,
@zburke included comment with reason + made disable more specific

> If you think the rules are wrong, then open a Jira explaining which rule needs to be changed and why

rule is fine, but linter is not so smart for our stripes-connect usage :)

2023-08-17 15:12 UTC, zburke approved these changes

2023-08-22 09:03 UTC, merged