UIPFU-76 Revert - ECS - 'Do not display shadow users in search results'
folio-org/ui-plugin-find-user pull request #244
Opened 2023-10-06 12:06 UTC by usavkov-epam

## Purpose

https://issues.folio.org/browse/UIPFU-76

## Approach

As far as filtering by user type was implemented (https://github.com/folio-org/ui-users/pull/2555), the search query should not exclude "shadow" users. So this PR reverts functionality to the previous state.

## Screenshots

https://github.com/folio-org/ui-plugin-find-user/assets/88109087/5205968c-27e3-433b-ab25-1907455a58bd

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-10-06 12:13 UTC, NikitaSedyx approved these changes

2023-10-06 12:38 UTC, BogdanDenis approved these changes

2023-10-06 12:39 UTC, BogdanDenis requested changes
Please also remove CHANGELOG entry

2023-10-06 13:28 UTC, Terala-Priyanka requested changes
Please remove the entry in changelog.md and also write a summary in the PR description and also on the associated ticket as to why the changes are being reverted. This will be helpful for future visitors of the PR and ticket.

2023-10-06 16:02 UTC, BogdanDenis approved these changes

2023-10-09 08:11 UTC, BogdanDenis approved these changes

2023-10-09 13:57 UTC, merged