UIPFU-77 - Add 'User assignment status' filter group
folio-org/ui-plugin-find-user pull request #249
Opened 2024-01-10 07:53 UTC by Terala-Priyanka

## Purpose

## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2024-01-10 15:34 UTC, BogdanDenis requested changes

2024-01-10 15:34 UTC, BogdanDenis commented on src/utils.js
> +  const condForOneOfTheFilters = (u) => activeFilterState?.active?.includes(u.active ? `${ACTIVE}` : `${INACTIVE}`) || activeFilterState?.pg?.includes(u.patronGroup);
I think this can be simplified. This implementation relies too much on knowledge of other filters. Right now there are only 2 other - Status and Patron group. If another filter needs to be added in the future this logic will have to be updated to work for 3 or more.
We need a general approach for user search to be easily extendable.
I think we should follow approach described in this comment - https://issues.folio.org/browse/UIU-1904?focusedCommentId=91751&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-91751

We can skip a call to `/perms/users` because we already have a list of user ids assigned current permission set
So the algorithm could be:
1. Get a list of assigned users (done, that's the `initialSelectedUsers` prop)
2. Search users by all filters, except for Assignment status - can be done by removing this filter in `buildQuery` function
3. Based on selected Assignment status filter, in https://github.com/folio-org/ui-plugin-find-user/blob/5ad35b64736552e92ad5de103ea9c4a0e2dd4846/src/UserSearchContainer.js#L198 filter users data
    - if "assigned" is selected - from search results select only those users that are also in `initialSelectedUsers`
    - if "unassigned" is selected - remove all users from search results that are not in `initialSelectedUsers`
    - if both or none are selected - don't make any changes to search results

2024-01-11 05:57 UTC, Terala-Priyanka commented on src/utils.js
> +    const alteredfilters = newRData.query.filters.split(',').filter(str => !str.startsWith(`${UAS}`)).join(',');
uas.Assigned should be removed in any case, as it will never participate in cql formation. So here the logic is appropriate. I see a need to update the comment above this code of line. Thank you.

2024-01-11 06:05 UTC, Terala-Priyanka commented on src/utils.js
> +    * When Assigned filter is selected on 'User assigbment Status' filter group, in any combination of filters in other filter groups,
For any combination (from other filter groups) with "Assigned" filter, there is no need to fetch the users once again(as the users list is already available through `initialSelectedUsers `prop) and hence we don't need any filters to parcipate in cql formation. 
`getUsersBasedOnAssignmentStatus` does the needful.

2024-01-11 06:23 UTC, Terala-Priyanka commented on src/utils.js
> +    if (filterCheck) {
`filterCheck ` argument is not always needed. Function overloading is used here.
![image](https://github.com/folio-org/ui-plugin-find-user/assets/104053200/52bb7df6-0644-4533-9335-55d9976ade88)

2024-01-11 13:50 UTC, BogdanDenis requested changes

2024-01-11 13:50 UTC, BogdanDenis commented on src/UserSearchContainer.js
> +      let otherFilterGroups = activeFilters.split(',').filter(f => !f.includes(`${UAS}`)).map(f => f.split('.')[0]);
We don't need check other filter values because this result list is alredy returned from back-end for a search with these filters. We just need to select from fetched users assigned or not assigned based on uas filter value

```
if (activeFilters.includes(`${UAS}`)) {
      const assignedUserIds = Object.keys(initialSelectedUsers);
      
      const uasFilterValues = activeFilters.split(',').filter(f => f.find(`${UAS}`));
      
      // both or neither Assignment status values are selected, so we can return result from BE
      if (uasFilterValues.length === 2 || uasFilterValues.length === 0) {
        return fetchedUsers;
      }
      
      if (uasFilterValues.includes(ASSIGNED_FILTER_KEY)) {
        return fetchedUsers.filter(user => assignedUserIds.includes(user.id));
      } else {
        return fetchedUsers.filter(user => !assignedUserIds.includes(user.id));
      }
}

return fetchedUsers;
```

2024-01-11 14:27 UTC, Terala-Priyanka commented on src/UserSearchContainer.js
> +      let otherFilterGroups = activeFilters.split(',').filter(f => !f.includes(`${UAS}`)).map(f => f.split('.')[0]);
Thank you again for your review!
 I agree that it is not needed for Unassigned filter as we are propagating the filters to make cql. But I think it is needed in case of Assigned filter as we are not propagating the filter string to make the cql(as we don't actually need to fetch)

2024-01-12 11:46 UTC, artem-blazhko requested changes
Could you cover new functionality in UserSearchContainer.js file by jest/RTL tests?

2024-01-12 11:46 UTC, artem-blazhko commented on src/UserSearchContainer.js
> +  const updatedResourceData = props.initialSelectedUsers && resourceData?.query?.filters?.includes(`${UAS}`) ? updateResourceData(resourceData) : resourceData;
```suggestion
  const updatedResourceData = props.initialSelectedUsers && resourceData?.query?.filters?.includes(UAS) ? updateResourceData(resourceData) : resourceData;
```

2024-01-12 11:46 UTC, artem-blazhko commented on src/UserSearchContainer.js
> +    if (activeFilters === `${ASSIGNED_FILTER_KEY}`) return assignedUsers;
```suggestion
    if (activeFilters === ASSIGNED_FILTER_KEY) return assignedUsers;
```

2024-01-12 11:46 UTC, artem-blazhko commented on src/UserSearchContainer.js
> +    if (activeFilters.includes(`${UAS}`)) {
```suggestion
    if (activeFilters.includes(UAS)) {
```

2024-01-12 11:46 UTC, artem-blazhko commented on src/UserSearchContainer.js
> +      const hasBothUASFilters = activeFilters.includes(`${ASSIGNED_FILTER_KEY}`) && activeFilters.includes(`${UNASSIGNED_FILTER_KEY}`);
```suggestion
      const hasBothUASFilters = activeFilters.includes(ASSIGNED_FILTER_KEY) && activeFilters.includes(UNASSIGNED_FILTER_KEY);
```

2024-01-12 11:46 UTC, artem-blazhko commented on src/UserSearchContainer.js
> +      const uasFilterValue = activeFilters.split(',').filter(f => f.includes(`${UAS}`))[0].split('.')[1];
```suggestion
      const hasNoneOfUASFilters = !activeFilters.includes(ASSIGNED_FILTER_KEY) && !activeFilters.includes(UNASSIGNED_FILTER_KEY);
      const uasFilterValue = activeFilters.split(',').filter(f => f.includes(UAS))[0].split('.')[1];
```

2024-01-12 11:46 UTC, artem-blazhko commented on src/UserSearchContainer.js
> +      if (uasFilterValue === `${ASSIGNED}`) {
```suggestion
      if (uasFilterValue === ASSIGNED) {
```

2024-01-12 11:46 UTC, artem-blazhko commented on src/UserSearchContainer.js
> +  getUsers = () => {
I would suggest to move this function outside the component. I will much easier to test all `if...else` conditions. 
But it is up to you.

2024-01-12 11:46 UTC, artem-blazhko commented on src/utils.js
> +  if (filterString === `${UNASSIGNED_FILTER_KEY}` || filterString === `${ASSIGNED_FILTER_KEY},${UNASSIGNED_FILTER_KEY}` || filterString === `${UNASSIGNED_FILTER_KEY},${ASSIGNED_FILTER_KEY}`) {
```suggestion
  if (filterString === UNASSIGNED_FILTER_KEY || filterString === `${ASSIGNED_FILTER_KEY},${UNASSIGNED_FILTER_KEY}` || filterString === `${UNASSIGNED_FILTER_KEY},${ASSIGNED_FILTER_KEY}`) {
```

2024-01-12 11:46 UTC, artem-blazhko commented on src/utils.js
> +    const alteredfilters = newRData.query.filters.split(',').filter(str => !str.startsWith(`${UAS}`)).join(',');
```suggestion
    const alteredfilters = newRData.query.filters.split(',').filter(str => !str.startsWith(UAS)).join(',');
```

2024-01-12 11:46 UTC, artem-blazhko commented on src/utils.test.js
> +    [`${UNASSIGNED_FILTER_KEY}`, `${ASSIGNED_FILTER_KEY},${UNASSIGNED_FILTER_KEY}`, `${UNASSIGNED_FILTER_KEY},${ASSIGNED_FILTER_KEY}`].forEach(filterStr => (
```suggestion
    [UNASSIGNED_FILTER_KEY, `${ASSIGNED_FILTER_KEY},${UNASSIGNED_FILTER_KEY}`, `${UNASSIGNED_FILTER_KEY},${ASSIGNED_FILTER_KEY}`].forEach(filterStr => (
```

2024-01-12 12:21 UTC, Terala-Priyanka commented
> Could you cover new functionality in UserSearchContainer.js file by jest/RTL tests?

Hey @artem-blazhko 
We will soon start working on migrating to Jest/RTL. So this file will be covered in the scope of that ticket that is there in our backlog.

2024-01-12 13:46 UTC, artem-blazhko commented on src/UserSearchContainer.js
> +      const hasBothUASFilters = activeFilters.includes(`${ASSIGNED_FILTER_KEY}`) && activeFilters.includes(UNASSIGNED_FILTER_KEY);
```suggestion
      const hasBothUASFilters = activeFilters.includes(ASSIGNED_FILTER_KEY) && activeFilters.includes(UNASSIGNED_FILTER_KEY);
```

2024-01-12 13:57 UTC, artem-blazhko approved these changes

2024-01-15 11:18 UTC, BogdanDenis approved these changes

2024-01-16 05:49 UTC, merged