UIPFU-87 - fix pagination issue
folio-org/ui-plugin-find-user pull request #256
Opened 2024-04-22 10:46 UTC by Terala-Priyanka

## Purpose

## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2024-04-22 15:57 UTC, BogdanDenis requested changes

2024-04-22 15:57 UTC, BogdanDenis commented on src/UserSearchContainer.js
> +    if(index/askAmount < 1) {
This works, but I think simple `index < askAmount` is more understandable

2024-04-22 15:58 UTC, artem-blazhko reviewed
Could you cover new functionality by tests?

2024-04-22 15:58 UTC, artem-blazhko commented on src/UserSearchContainer.js
> +    if(index/askAmount < 1) {
Could you fix ESLint errors here?

2024-04-22 15:58 UTC, artem-blazhko commented on src/UserSearchContainer.js
> +        This condition sets offset to 100 when there are less than 100 records in the current
Could you fix ESLint errors here?

2024-04-22 15:58 UTC, artem-blazhko commented on src/UserSearchContainer.js
> +      index = 100;
Could you fix ESLint errors here?

2024-04-22 16:14 UTC, manvendra-s-rathore commented
> Could you cover new functionality by tests?

We have a tech debt to cover this later on. [UIPFU-78](https://folio-org.atlassian.net/browse/UIPFU-78)

2024-04-22 17:09 UTC, artem-blazhko approved these changes

2024-04-23 08:55 UTC, BogdanDenis approved these changes

2024-04-23 09:06 UTC, merged