UIPFU-81 - Add jest tests to Filters.js
folio-org/ui-plugin-find-user pull request #274
Opened 2024-08-30 07:20 UTC by Terala-Priyanka

## Purpose

## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2024-09-04 08:59 UTC, mariia-aloshyna commented on src/Filters.test.js
> +    const inActiveCheckbox = document.querySelector('[ id = "clickable-filter-active-inactive"]');
is it possible to find the checkbox using `getByRole()`?

2024-09-04 08:59 UTC, mariia-aloshyna commented on test/jest/helpers/renderWithRouter.js
> +
remove an extra blank line, please

2024-09-04 09:00 UTC, BogdanDenis requested changes

2024-09-04 09:00 UTC, BogdanDenis commented on src/Filters.test.js
> +import { screen } from '@folio/jest-config-stripes/testing-library/react';
Please re-order imports so that first we import third-party modules, then stripes modules, and last is imports from current module. Please also check other files in this PR

2024-09-04 09:21 UTC, Terala-Priyanka commented on package.json
> +    "history": "^5.0.0",
Hey @BogdanDenis 
Thank you for bringing this up.
I have noticed that `history ` v5 is used with `react-router@5` within `ui-users`.
It works seamlessly in the workflows too.

Could you please share if there is anything specific about this incompatibility?

2024-09-04 09:27 UTC, mariia-aloshyna approved these changes

2024-09-04 14:37 UTC, BogdanDenis commented on package.json
> +    "history": "^5.0.0",
@Terala-Priyanka we've had some test errors because `history.listen` was called with a slightly different `location` argument structure in tests versus in real application. It was a difficult issue to debug because I also assumed that `history@5` is supposed to be used with `react-router@5`

2024-09-05 05:58 UTC, Terala-Priyanka commented on src/Filters.test.js
> +import { screen } from '@folio/jest-config-stripes/testing-library/react';
Hey @BogdanDenis 
Thank you for the insights. I have pushed the change. Could you please re-review it?

2024-09-05 08:28 UTC, BogdanDenis approved these changes

2024-09-05 08:52 UTC, merged